/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sofishtication.Views;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import sofishtication.Models.ApiRequester;

/**
 *
 * @author user-pc
 */
public class JokesPanel extends javax.swing.JPanel {
    
    public JokesPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedPanel1 = new sofishtication.Views.FeedPanel();
        jokeCard1 = new sofishtication.Views.JokeCard();

        setLayout(new java.awt.CardLayout());

        feedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                feedPanel1MousePressed(evt);
            }
        });
        add(feedPanel1, "feed");
        add(jokeCard1, "card");
    }// </editor-fold>//GEN-END:initComponents

    private void feedPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedPanel1MousePressed

    }//GEN-LAST:event_feedPanel1MousePressed
    private void setCard(String card) {
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, card);
    }
    
    public void openProfile(ApiRequester apiReq) {
        jokeCard1.setApiReq(apiReq);
        setCard("card");
    }
    
    public void closeProfile() {
        jokeCard1.setApiReq(null);
        setCard("feed");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sofishtication.Views.FeedPanel feedPanel1;
    private sofishtication.Views.JokeCard jokeCard1;
    // End of variables declaration//GEN-END:variables
}
